# Joint controller configuration parameters
  /controller_joint/run_period: 0.001          # Node execution period
  /controller_joint/start_delay: 0.5          # Execution start delay

  /controller_joint/Kp_pos: [35.0, 35.0, 35.0]        # Position control, proportional gains
  /controller_joint/uMin_pos: [-200, -200, -200]  # Position control, low saturation
  /controller_joint/uMax_pos: [200, 200,200]    # Position control, high saturation

  /controller_joint/Kp_vel: [3.92, 2.74, 2.74]       # Velocity control, proportional gains
  /controller_joint/Ti_vel: [0.05, 0.05, 0.05]       # Velocity control, integral time
  /controller_joint/uMin_vel: [-200, -200, -200]  # Velocity control, low saturation
  /controller_joint/uMax_vel: [200, 200, 200]    # Velocity control, high saturation

