# Joint planner configuration parameters
  /planner_joint/run_period: 0.001          # Node execution period
  /planner_joint/start_delay: 0.5          # Execution start delay

  /planner_joint/trajectoryType: 1         # Trajectory type: 1, trapezoidal; 2, polynomial

  /planner_joint/qi: [0.0,0.0,0.0]            # Initial joint positions [rad]
  /planner_joint/qf: [1000, 1000, 1000]         # Final joint positions [rad]

  /planner_joint/max_ang_acc: [10, 10, 10]   # Maximum angular acceleration (for trapezoidal trajectory) [rad/s^2]
  /planner_joint/max_ang_vel: [100, 100, 100]   # Maximum angular velocity (for trapezoidal trajectory) [rad/s]

# giuste velocità 0.663, 0.663, 0.663

  /planner_joint/tf: 5.0                   # Trajectory duration (for polynomial trajectory) [s]

